export const skilldata = [

    "JavaScript",
    "Python",
    "Java",
    "C++",
    "Go",
    "Swift",
    "Kotlin",
    "Rust",
    "Ruby",
    "TypeScript",
    "React.js",
    "Node.js",
    "Angular",
    "Vue.js",
    "Django",
    "Flask",
    "Ruby on Rails",
    "Spring Boot",
    "MySQL",
    "MongoDB",
    "PostgreSQL",
    "Firebase",
    "AWS",
    "Google Cloud Platform",
    "Microsoft Azure",
    "Kubernetes",
    "Docker",
    "Terraform",
    "GraphQL",
    "Next.js",
    "REST APIs",

    "TensorFlow",
    "PyTorch",
    "Machine Learning",
    "Data Science",
    "Data Analytics",
    "Blockchain",
    "Cybersecurity",
    "DevOps",
    "CI/CD",
    "Git",
    "GitHub",
    "Jenkins",
    "Prometheus",

];

export const technicalInterests = [

    "Artificial Intelligence",
    "Machine Learning",
    "Deep Learning",
    "Natural Language Processing",
    "Data Science",
    "Big Data",
    "Blockchain",
    "Cryptocurrency",
    "Cloud Computing",
    "IoT (Internet of Things)",
    "Augmented Reality (AR)",
    "Virtual Reality (VR)",
    "Edge Computing",
    "Quantum Computing",
    "Cybersecurity",
    "Robotics",
    "AI Ethics",
    "5G Technology",
    "Smart Cities",
    "Automation",
    "Digital Transformation",
    "Augmented Reality",
    "Decentralized Finance (DeFi)",
    "Self-Driving Cars",
    "Cloud Security",
    "Edge AI",
    "Data Privacy",
    "Wearable Technology",
    "Tech Startups"
];
